### PR TITLE
Intial commit

### PR DESCRIPTION
**Pull request by kentbarber**
Support for R21 OSX.

### CODE REVIEW

**Comment by NiklasRosenstein** [comment]
Hey @kentbarber , why'd you close the PR again? 😃

**Comment by kentbarber** [comment]
I mistakenly did a PR to your repo instead of my own. So I closed it since it wasn’t intended to be merged into your repo due to the different approach to building the plugin. 

I was asked if could get it going in R21 for someone. Was a nice Saturday morning project. Will post up builds for OSX and Windows sometime soon.

Nice work on the port. Everything working as expected so far.

Best Regards,
Kent

**Comment by NiklasRosenstein** [comment]
Gotcha -- thanks for porting it to R21. I can give you permissions on this repo then you can push here and make a GitHub release for R21. OK for you?

**Comment by kentbarber** [comment]
Thanks Niklas, but I might put them up either on my github or some other
site. I am considering setting up an automated build system to build and
release multiple GPL based projects for users so will keep them all in one
location.

**Pull request closed without merging**
